config/routes.rb
Rails.application.routes.draw do
    get 'top/main'
    post 'top/login'
    root 'top#main'
    get 'top/logout'
    get 'top/newuser'
    post 'top/saveuser'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid] != nil
      render "main"
    else
      render "login"
    end
  end

  def login
    user = User.find_by(uid: params[:uid])
    if user != nil
      if BCrypt::Password.new(user.pass) == params[:pass]
        session[:login_uid] = params[:uid]
        redirect_to top_main_path
      else
        render "error"
      end
    else
      render "error"
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to top_main_path
  end

  def newuser
    render "newuser"
  end

  def saveuser
    #uidの存在チェック
    if User.find_by(uid: params[:uid])
      #あったら、既に登録済みエラー画面
      render "exist_error"
    else
      #なかったら、パスワードの暗号化、User.Create（）、登録完了画面
      User.create(uid: params[:uid], pass: BCrypt::Password.create(params[:pass]))
      render "registered"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<h1>エラー</h1>

<%= link_to '戻る', :back %>

app/views/top/exist_error.html.erb
<h1>すでに登録済みです。</h1>

<%= link_to '戻る', :back %>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post, data: { turbo: false} do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %><br>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %><br>
    <%= submit_tag 'ログイン' %><br>
    <%= link_to '新規ユーザー登録', top_newuser_path %>
<% end %>

app/views/top/main.html.erb
<h1>ログイン中です！</h1>

<%= link_to 'ログアウト', top_logout_path %>

app/views/top/newuser.html.erb
<h1>「新規ユーザー登録」</h1>

<%= form_tag '/top/saveuser', method: :post, data: { turbo: false} do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %><br>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %><br>
    <%= submit_tag '登録' %><br>
    <%= link_to 'ログインへ戻る', top_logout_path %>
<% end %>

app/views/top/registered.html.erb
<h1>登録が完了しました。</h1>

<%= link_to '戻る', :back %>